# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your application code to the container
COPY . .

# Build your React application
RUN npm run build

# Expose the port on which your React app will run
EXPOSE 3000

# Start your React application
CMD ["npm", "start"]
